repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [-l 120, -S]
        description: 'black formatting with quotes maintained, and max length at col 120'

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        description: 'flake8 linting'
        args: [--max-line-length=120]
        description: 'flake8 linting with max length at col 120'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 6e63c9e
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
